### ISSUE TITLE
Deploy knaitve does not work

### ISSUE THREAD

**Issue by VolITSol** [drogue-iot/drogue-cloud-helm-charts#19]
Dear all,

I try to deploy drogue on our openshift cluster. Calling at _knative.sh

kubectl apply -f https://github.com/knative/serving/releases/download/v0.24.1/serving-core.yaml

I get following error  - amy idea what's wrong?!

Thanks a lot :-)

Error from server (InternalError): error when creating "https://github.com/knative/serving/releases/download/v0.24.1/serving-core.yaml": Internal error occurred: failed calling webhook "config.webhook.serving.knative.dev": Post "https://webhook.knative-serving.svc:443/config-validation?timeout=10s": no endpoints available for service "webhook"
Error from server (InternalError): error when creating "https://github.com/knative/serving/releases/download/v0.24.1/serving-core.yaml": Internal error occurred: failed calling webhook "config.webhook.serving.knative.dev": Post "https://webhook.knative-serving.svc:443/config-validation?timeout=10s": no endpoints available for service "webhook"
Error from server (InternalError): error when creating "https://github.com/knative/serving/releases/download/v0.24.1/serving-core.yaml": Internal error occurred: failed calling webhook "config.webhook.serving.knative.dev": Post "https://webhook.knative-serving.svc:443/config-validation?timeout=10s": no endpoints available for service "webhook"
Error from server (InternalError): error when creating "https://github.com/knative/serving/releases/download/v0.24.1/serving-core.yaml": Internal error occurred: failed calling webhook "config.webhook.serving.knative.dev": Post "https://webhook.knative-serving.svc:443/config-validation?timeout=10s": no endpoints available for service "webhook"
Error from server (InternalError): error when creating "https://github.com/knative/serving/releases/download/v0.24.1/serving-core.yaml": Internal error occurred: failed calling webhook "config.webhook.serving.knative.dev": Post "https://webhook.knative-serving.svc:443/config-validation?timeout=10s": no endpoints available for service "webhook"
Error from server (InternalError): error when creating "https://github.com/knative/serving/releases/download/v0.24.1/serving-core.yaml": Internal error occurred: failed calling webhook "config.webhook.serving.knative.dev": Post "https://webhook.knative-serving.svc:443/config-validation?timeout=10s": no endpoints available for service "webhook"
Error from server (InternalError): error when creating "https://github.com/knative/serving/releases/download/v0.24.1/serving-core.yaml": Internal error occurred: failed calling webhook "config.webhook.serving.knative.dev": Post "https://webhook.knative-serving.svc:443/config-validation?timeout=10s": no endpoints available for service "webhook"
Error from server (InternalError): error when creating "https://github.com/knative/serving/releases/download/v0.24.1/serving-core.yaml": Internal error occurred: failed calling webhook "config.webhook.serving.knative.dev": Post "https://webhook.knative-serving.svc:443/config-validation?timeout=10s": no endpoints available for service "webhook"
Error from server (InternalError): error when creating "https://github.com/knative/serving/releases/download/v0.24.1/serving-core.yaml": Internal error occurred: failed calling webhook "config.webhook.serving.knative.dev": Post "https://webhook.knative-serving.svc:443/config-validation?timeout=10s": no endpoints available for service "webhook"
Error from server (InternalError): error when creating "https://github.com/knative/serving/releases/download/v0.24.1/serving-core.yaml": Internal error occurred: failed calling webhook "config.webhook.serving.knative.dev": Post "https://webhook.knative-serving.svc:443/config-validation?timeout=10s": no endpoints available for service "webhook"
Error from server (InternalError): error when creating "https://github.com/knative/serving/releases/download/v0.24.1/serving-core.yaml": Internal error occurred: failed calling webhook "config.webhook.serving.knative.dev": Post "https://webhook.knative-serving.svc:443/config-validation?timeout=10s": no endpoints available for service "webhook"

**Comment by ctron** [comment]
It looks like the knative webhook service didn't come up. If would be helpful to have the log output and the description of the failing pods (I guess in the `knative-serving` namespace).

If you are running on OpenShift, I think you should also have access to "OpenShift Serverless". So you don't need to install knative yourself. That might be easier in the end. Same for Strimzi (which is AMQ Streams). You can disable installing the dependencies by setting the environment variable `INSTALL_DEPS` to `false` when starting the installer:

```shell
env INSTALL_DEPS=false ./scripts/drgadm deploy ...
```

Or, for only disabling Knative:

```shell
env INSTALL_KNATIVE=false ./scripts/drgadm deploy ...
```

Knative is also only required if you want to deploy the example setup together with the core deployment. This is the default with the installer script. You can disable the example deployment using the `-e` switch.

**Comment by VolITSol** [comment]
Thanks a lot for the different hints...:-)!

Now Drogue starts to deploy! However, different pods cannot start because of this error:

Error: error sending request for url (https://sso.apps.ocdev.company.local/auth/realms/drogue/.well-known/openid-configuration): error trying to connect: invalid certificate: UnknownIssuer


[2022-02-17T14:16:33Z INFO  drogue_cloud_device_management_service] Running device management service!
[2022-02-17T14:16:33Z INFO  drogue_cloud_service_common::reqwest] Adding root certificate: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
[2022-02-17T14:16:33Z INFO  drogue_cloud_service_common::reqwest] Found 1 certificates
[2022-02-17T14:16:33Z INFO  drogue_cloud_service_common::reqwest] Adding root certificate: Certificate
[2022-02-17T14:16:33Z WARN  rustls::session] Sending fatal alert BadCertificate
Error: error sending request for url (https://sso.apps.ocdev.company.local/auth/realms/drogue/.well-known/openid-configuration): error trying to connect: invalid certificate: UnknownIssuer

Please can you give me some other hints, how I can fix this?!

Thank you:-)

**Comment by ctron** [comment]
Hm, it looks like the Keycloak/SSO endpoint (route) is served with a certificate, which is not trusted by the drogue cloud components (which by default is the system CA pool, plus the OpenShift service CA).

Taking a look at the current helm charts, I can't see a way to use "insecure" TLS with SSO. It is possible to configure the SSO ingress setting in the Helm values:

```yaml
drogueCloudCore:
  services:
    sso:
      ingress:
        host: <hostname>
        proto: http # change from https to http
```

However, for this to work. Keycloak must indeed be accessible using `http`.

**Comment by VolITSol** [comment]
Jens,

this ist from Keycloak pod log:

WFLYELY00024: Certificate [dstrootcax3] in KeyStore is not valid: java.security.cert.CertificateExpiredException: NotAfter: Thu Sep 30 14:01:15 GMT 2021
Is this a problem from the Keycloak 15.0.1 version used by drgadm deploy?
Can I use a newer version?

Thanks again for your help!!

[0m[33m09:39:36,747 WARN  [org.wildfly.extension.elytron] (MSC service thread 1-1) WFLYELY00023: KeyStore file '/opt/jboss/keycloak/standalone/configuration/application.keystore' does not exist. Used blank.
[0m[33m09:39:36,761 WARN  [org.wildfly.extension.elytron] (MSC service thread 1-2) WFLYELY00024: Certificate [dstrootcax3] in KeyStore is not valid: java.security.cert.CertificateExpiredException: NotAfter: Thu Sep 30 14:01:15 GMT 2021
	at java.base/sun.security.x509.CertificateValidity.valid(CertificateValidity.java:277)
	at java.base/sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:675)
	at java.base/sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:648)
	at org.wildfly.extension.elytron@18.0.4.Final//org.wildfly.extension.elytron.KeyStoreService.checkCertificatesValidity(KeyStoreService.java:230)
	at org.wildfly.extension.elytron@18.0.4.Final//org.wildfly.extension.elytron.KeyStoreService.start(KeyStoreService.java:192)
	at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)
	at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)
	at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1363)
	at java.base/java.lang.Thread.run(Thread.java:829)

[0m[33m09:39:36,762 WARN  [org.wildfly.extension.elytron] (MSC service thread 1-2) WFLYELY00024: Certificate [globalsignrootca-r2] in KeyStore is not valid: java.security.cert.CertificateExpiredException: NotAfter: Wed Dec 15 08:00:00 GMT 2021
	at java.base/sun.security.x509.CertificateValidity.valid(CertificateValidity.java:277)
	at java.base/sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:675)
	at java.base/sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:648)
	at org.wildfly.extension.elytron@18.0.4.Final//org.wildfly.extension.elytron.KeyStoreService.checkCertificatesValidity(KeyStoreService.java:230)
	at org.wildfly.extension.elytron@18.0.4.Final//org.wildfly.extension.elytron.KeyStoreService.start(KeyStoreService.java:192)
	at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)
	at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)
	at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1363)
	at java.base/java.lang.Thread.run(Thread.java:829)

[0m[33m09:39:36,762 WARN  [org.wildfly.extension.elytron] (MSC service thread 1-2) WFLYELY00024: Certificate [cybertrustglobalroot] in KeyStore is not valid: java.security.cert.CertificateExpiredException: NotAfter: Wed Dec 15 08:00:00 GMT 2021
	at java.base/sun.security.x509.CertificateValidity.valid(CertificateValidity.java:277)
	at java.base/sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:675)
	at java.base/sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:648)
	at org.wildfly.extension.elytron@18.0.4.Final//org.wildfly.extension.elytron.KeyStoreService.checkCertificatesValidity(KeyStoreService.java:230)
	at org.wildfly.extension.elytron@18.0.4.Final//org.wildfly.extension.elytron.KeyStoreService.start(KeyStoreService.java:192)
	at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)
	at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)
	at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1363)
	at java.base/java.lang.Thread.run(Thread.java:829)

[0m[0m09:39:36,783 INFO  [org.jboss.as.patching] (MSC service thread 1-2) WFLYPAT0050: Keycloak cumulative patch ID is: base, one-off patches include: none
[0m[33m09:39:36,784 WARN  [org.wildfly.extension.elytron] (MSC service thread 1-2) WFLYELY01084: KeyStore /opt/jboss/keycloak/standalone/configuration/application.keystore not found, it will be auto generated on first use with a self-signed certificate for host localhost
[0m[0m09:39:36,822 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-2) WFLYSRV0027: Starting deployment of "keycloak-server.war" (runtime-name: "keycloak-server.war")
[0m[0m09:39:36,825 INFO  [org.jboss.as.server.deployment.scanner] (MSC service thread 1-2) WFLYDS0013: Started FileSystemDeploymentService for directory /opt/jboss/keycloak/standalone/deployments
[0m[0m09:39:36,911 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-1) WFLYUT0012: Started server default-server.
[0m[0m09:39:36,950 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-2) WFLYUT0006: Undertow AJP listener ajp listening on 0.0.0.0:8009
[0m[0m09:39:36,963 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-2) WFLYUT0006: Undertow HTTP listener default listening on 0.0.0.0:8080

**Comment by ctron** [comment]
That actually looks good. And for the CI is just works. And same for me, just deployed a few instances locally today.

So unfortunately the issue must be with your setup. But let's find out what goes wrong.

Can you give some hints on how you set up your cluster? Ideally the steps you took to run into this problem.

**Comment by ctron** [comment]
Ok, I am trying to replicate this with `crc`, and I think I understand what might be wrong.

I assume you don't have "proper" (trusted) certificates installed. CRC uses self-signed certificates by default. So all OpenShift routes get created with a self-signed certificate. So far, we can only handle either `http` or `https` (with a valid certificate). For the latter, we also add the OpenShift service CA automatically.

However, what happens when running with a developer OpenShift instance, which does not have trusted certificates is, the OAuth clients cannot access the SSO instance (keycloak) as the certificate is not trusted.

And currently, there is no way around that, as we enforce https on OpenShift.

The proper solution would be use trusted certificates (e.g. from Let's Encrypt) :grin: 

However, I absolutely get the point of setting up a developer scenario without. So, I will try to do the following:

* Change the help charts to not enforce `https` on OpenShift, but make it a default instead. That way you should be able to deploy it the same way it is done on Minikube and Kind
* Allow setting some "tls insecure" flag. However, that means a code change, and a new release (unless you want to run "latest")
* Allow providing an explicit TLS certificate for validating. Again, a code change.

**Comment by ctron** [comment]
Ok, looks like the first idea (downgrading to `http` doesn't work, as Keycloak always turns on TLS (which isn't bad). But you can't downgrade an `https` endpoint to `http` in OpenShift (which also isn't bad). Still, it doesn't help.

**Comment by ctron** [comment]
Code changes are here: https://github.com/drogue-iot/drogue-cloud/pull/236

**Comment by ctron** [comment]
I just merged the changes. It works on a local CRC instance now. Which should be the same setup as an OpenShift cluster with self-signed certificates.

It will take a bit until new images are being pushed, and you need to use the Helm charts directly from this git repository (or use `make deploy` from the `drogue-cloud` repository). This will be in the 0.9 release, but we don't have a date for that yet.

**Comment by VolITSol** [comment]
Jens, thanks a lot for YOUR SUPPORT!!!

Will try it as soon as new images are available...

Best Christian

**Comment by VolITSol** [comment]
Jens,

Do you have an other idea:-)! Thanks a lot!!!!!

I always get ImagePullBackoff for some images...

E.G.:
Back-off pulling image "ghcr.io/drogue-iot/console-frontend:0.9.0"

 Warning  Failed          60m (x4 over 61m)    kubelet            Failed to pull image "ghcr.io/drogue-iot/console-frontend:0.9.0": rpc error: code = Unknown desc = Error reading manifest 0.9.0 in ghcr.io/drogue-iot/console-frontend: manifest unknown
  Warning  Failed          60m (x4 over 61m)    kubelet            Error: ErrImagePull
  Warning  Failed          59m (x6 over 61m)    kubelet            Error: ImagePullBackOff

[lxadmin@jumphost drogue-install]$ kubectl describe pod console-frontend-7b67cf8966-9fqb5
Name:         console-frontend-7b67cf8966-9fqb5
Namespace:    drogue-iot
Priority:     0
Node:         worker1/10.10.10.98
Start Time:   Mon, 14 Mar 2022 14:59:28 +0100
Labels:       app.kubernetes.io/component=console
              app.kubernetes.io/instance=drogue-iot
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=console-frontend
              app.kubernetes.io/part-of=drogue-iot
              app.kubernetes.io/version=0.9.0
              pod-template-hash=7b67cf8966
Annotations:  k8s.v1.cni.cncf.io/network-status:
                [{
                    "name": "openshift-sdn",
                    "interface": "eth0",
                    "ips": [
                        "10.128.2.236"
                    ],
                    "default": true,
                    "dns": {}
                }]
              k8s.v1.cni.cncf.io/networks-status:
                [{
                    "name": "openshift-sdn",
                    "interface": "eth0",
                    "ips": [
                        "10.128.2.236"
                    ],
                    "default": true,
                    "dns": {}
                }]
              openshift.io/scc: restricted
Status:       Pending
IP:           10.128.2.236
IPs:
  IP:           10.128.2.236
Controlled By:  ReplicaSet/console-frontend-7b67cf8966
Containers:
  endpoint:
    Container ID:
    Image:          ghcr.io/drogue-iot/console-frontend:0.9.0
    Image ID:
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Limits:
      memory:  64Mi
    Requests:
      memory:   64Mi
    Readiness:  http-get http://:8080/ delay=2s timeout=1s period=1s #success=1 #failure=3
    Environment:
      API_URL:  https://api.apps.ocdev.company.local
    Mounts:
      /endpoints from endpoints (rw)
      /etc/config/login from login-config (ro)
      /run from run (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-hgsgv (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  run:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  endpoints:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  login-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      login-config
    Optional:  true
  kube-api-access-hgsgv:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
    ConfigMapName:           openshift-service-ca.crt
    ConfigMapOptional:       <nil>
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason          Age                  From               Message
  ----     ------          ----                 ----               -------
  Normal   Scheduled       61m                  default-scheduler  Successfully assigned drogue-iot/console-frontend-7b67cf8966-9fqb5 to worker1
  Normal   AddedInterface  61m                  multus             Add eth0 [10.128.2.236/23] from openshift-sdn
  Normal   Pulling         60m (x4 over 61m)    kubelet            Pulling image "ghcr.io/drogue-iot/console-frontend:0.9.0"
  Warning  Failed          60m (x4 over 61m)    kubelet            Failed to pull image "ghcr.io/drogue-iot/console-frontend:0.9.0": rpc error: code = Unknown desc = Error reading manifest 0.9.0 in ghcr.io/drogue-iot/console-frontend: manifest unknown
  Warning  Failed          60m (x4 over 61m)    kubelet            Error: ErrImagePull
  Warning  Failed          59m (x6 over 61m)    kubelet            Error: ImagePullBackOff
  Normal   BackOff         85s (x263 over 61m)  kubelet            Back-off pulling image "ghcr.io/drogue-iot/console-frontend:0.9.0"
